service:
  name: brn-counter

myNextAppplication:
  component: "@sls-next/serverless-component@3.4.0"
  inputs:
    domain: ["counter", "onbrn.com"]
    bucketName: brn-counter
    bucketRegion: us-east-1
    build:
      env:
        NODE_PATH: "/"
